### ISSUE TITLE
Choose Software license

### ISSUE THREAD

**Issue by tiagoboldt** [ShiftForward/apso#46]
We should specify under which conditions this software can be used and add the proper license to the repository.

**Comment by andresilva** [comment]
`https://github.com/ShiftForward/apso/blob/master/LICENSE`

**Comment by tiagoboldt** [comment]
my bad :)

**Comment by tiagoboldt** [comment]
I'm not sure that is being used correctly. It says "you cannot use this file". Shouldn't it say project or source code?
